name = "vcdim_convex_bound_fc"
version = "0.1.0"
defaultTargets = ["VCDimConvexFC"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.33.1"

[[lean_lib]]
name = "VCDimConvexFC"

[[lean_lib]]
name = "VCDimConvex"
